### ISSUE TITLE
Photo not being sent

### ISSUE THREAD

**Issue by hussamh10** [nickoala/telepot#107]
I have been trying send photo through my bot but the photo never make it to the user and the program just stops there at the `sendPhoto()` function.

    import telepot
    bot = 0

    def handle(msg):   

        content_type, chat_type, chat_id = telepot.glance(msg)
        bot.sendMessage(chat_id, 'Hello')
        bot.sendPhoto(chat_id, open('l.jpg', 'rb'))

        print('sent')

    def main(): 
        global bot
        bot = telepot.Bot('BOT-TOKEN')
        bot.message_loop(handle)

        while True:
            pass

    main()
Also no error messages are displayed.

**Comment by zumoshi** [comment]
Hello,
i would replace `pass` in while loop with `sleep`, i think it uses a huge amount of cpu right now. you can also send a second parameter to message_loop and remove the while loop completely.

```python
bot.message_loop(handle, run_forever=True)
```

your code for sending the photo seems alright though. are you sure that image `l.jpg` exists and is in the same folder as your `.py` file ?
perhaps you can wrap the `sendPhoto` method in a `try` block to see if there is any error.

```python
import telepot
bot = 0

def handle(msg):   
    content_type, chat_type, chat_id = telepot.glance(msg)
    bot.sendMessage(chat_id, 'Hello')
    try:
        bot.sendPhoto(chat_id, open('l.jpg', 'rb'))
    except Exception as ex:
        print(ex)

    print('sent')

def main(): 
    global bot
    bot = telepot.Bot('BOT-TOKEN')
    bot.message_loop(handle, run_forever=True)

main()
```

i tested the above code now with `telepot 8.1` and `python 3.5.1` and it sent the photo.

**Comment by hussamh10** [comment]
Ok so i tested your code but still got the same results.
And yes l.jpg does exist in the same dir as the .py.

Anyway the thing is that i just tested my code with a much smaller photo (125 bytes) , to my surprise I did receive the photo but after 2-3 minutes.
So i guess after all the problem is not in the code. 

But I still have all those photos to send :P so any help will be appreciated.
Thanks. :)

**Comment by zumoshi** [comment]
to me that seems more of a network problem, what are you running the bot on ?
have you tried getting a VPS or switching your provider if you have one?

may be unrelated but try changing your token, for some strange reason telegram sometimes refuses to accept files from some tokens , also see #68 if using another token sent photos without problems.

**Comment by nickoala** [comment]
I encourage you to try sending photos in the Python interpreter (with a **real token**, of course):

```python
>>> import telepot
>>> bot = telepot.Bot('11111111:AAAAAAAAAAAAAAAAAAAAAAA')
>>> bot.sendPhoto(99999999, open('1.jpg', 'rb'))
```

Experiment with various file sizes, and note the time needed. I just send a file of 2.2M, and it took 30 seconds or so. Depends on the network of course.

According to my experience, as the file reaches a certain size (I forgot how large), it hangs there forever (or an HTTP timeout after a long time. I forgot which.) It seemed the sending was not successful. But after a few minutes, the recipient received the photo nonetheless.

At first, I suspect the problem was with the HTTP library, so I tried the same experiment with CURL. No different. I reported the problem to BotSupport. They acknowledged it, but never really fixed it for me. Last time I checked, it was at least 6 months ago, so I don't know how up-to-date my experience is. That's the whole story, all I can say.
