### ISSUE TITLE
Update telegram bot keyboard input

### ISSUE THREAD

**Issue by DarkC343** [nickoala/telepot#115]
I'm sort of new to python programming and I tried to figure out this problem but not successful some how. I want to create a list that a client can declare items in the list. I wrote these commands and I can just receive the first input from the keyboard (list). Obviously the list has it's own sub items that inherit from main item list. Here is the code:

[See the source code](http://pastebin.com/aghk0Tw6)

The output is like this:

[See the output screenshot
](http://i.stack.imgur.com/eAV5W.png)
The other thing that I want to solve is to avoid repetition of keyboard message show. How should I put the keyboard without a reply to client. The second argument in bot.sendMessage() cant be ignored and should be assigned

Special thanks to @nickoala

**Comment by zumoshi** [comment]
hello,
for the first problem , you don't have to resend the keyboard if it is not changed , so you can omit the message when not sending a new keyboard. and you can bring back the main keyboard in the same message that notifies the user a submenu item is pressed.

also, I would like to mention that the whole `handler` function is executed each time a message is sent to your bot. 

as for second problem (the nested if) you have a logical problem , when you nest two if's both conditions must be true (i.e. they are AND-ed) so this is your condition:
```python
if chat_message == 'Option #1' and chat_message == 'Sub option #1_1':
```
which is always false because it can't be both at the same time ...

you should either switch to a delegate bot and keep state of your bot (which keyboard is sent) in a user-specific variable and use that variable in your conditions; or if you don't need keys in different menus to have the same text you can try this code:

```python
import telepot

def handler(msg):
    chat_id = msg['chat']['id']
    chat_message = msg['text']
    
    main_keyboard = [['Option #1', 'Option #2'], ['Option #3', 'Option #4']]
    sub_keyboard = [['Sub option #1_1', 'Sub option #1_2'], ['Sub option #1_3', 'Sub option #1_4'],['Back to Main menu']]
    
    if chat_message=='/start':
        bot.sendMessage(chat_id, 'Main options', reply_markup={'keyboard': main_keyboard})
    elif chat_message in [j for i in main_keyboard for j in i]:
        # an option from Main keyboard is chosen:
        
        # Ex: Option #1 > You selected Option #1
        bot.sendMessage(chat_id, 'Main selected: %s' %chat_message)
        
        if chat_message == 'Option #1':
            sub_buttons = {'keyboard': sub_keyboard}
            bot.sendMessage(chat_id, 'Sub options', reply_markup=sub_buttons)
 
    elif chat_message in [j for i in sub_keyboard for j in i]:
        # an option from Sub keyboard is chosen:
        if chat_message == 'Sub option #1_1':
            bot.sendMessage(chat_id, 'Sub selected %s' %chat_message)
        if chat_message == 'Back to Main menu':
            bot.sendMessage(chat_id, 'Main options', reply_markup={'keyboard': main_keyboard})
            
    else:
        bot.sendMessage(chat_id, 'Invalid Message. please select an option from keyboard')
 
bot = telepot.Bot('191891323:AAHb42-2xFjUWc0M0dwx8CzafJUbUIuQUas')
print('[+] started...')
bot.message_loop(handler, run_forever=True)
```

it simply searches the message in the list of keyboard keys to detect which keyboard it belongs to, i took the search code from [here](http://stackoverflow.com/questions/11963711/what-is-the-most-efficient-way-to-search-nested-lists-in-python).

**Comment by DarkC343** [comment]
@zumoshi thank you so much for your helpful reply :+1: :100:

**Comment by zumoshi** [comment]
if you looked at the end of my message I did provide a link to explain that part.
it simply works like `if 'something' in sub_keyboard:` to check if `'something'` exists in `sub_keyboard` or not , but it also searches inside the nested lists.
because the `sub_keyboard` is a list of lists simply writing `if 'something' in sub_keyboard:` wouldn't work.
