### ISSUE TITLE
Problems with Google App Engine

### ISSUE THREAD

**Issue by Suyash458** [nickoala/telepot#123]
This package doesn't seem to work with the free plan of Google App Engine since it allows for only one thread of execution. [Here's](http://pastebin.com/tTQN085m) the error log which I was getting. 

Will setting the 'num_pools' and 'max_size' parameters to 1 and setting 'block' to True in 'api.py'(Line 11) make any difference?

**Comment by nickoala** [comment]
No, they won't make any difference. In traditional version, delegates are threads, and there is no easy way to get around it. In async version, delegates are tasks, and you may be able to use that on GAE.

For more details, please refer to Issue #55. Simply put, there is no easy way get around this limitation.

**Comment by Suyash458** [comment]
Thank you! I'll look into the async version. Are multiple threads spawned even if you call handle() directly? 
https://github.com/nickoala/telepot/issues/55#issuecomment-212415652

**Comment by nickoala** [comment]
Calling `handle()` does not spawn threads.

But the thing about threads as related to [that comment](https://github.com/nickoala/telepot/issues/55#issuecomment-212415652) is that, in a traditional web server, a thread may be spawned to handle each HTTP request. Since `handle()` by itself is not thread-safe, calling it directly as suggested by that comment is not safe *generally* (because many threads may be calling it at the same time). But *in the context of Flask*, it is safe because the Flask webserver is single-threaded (because it is only for testing, not for deployment). I hope this makes it clear.

**Comment by Suyash458** [comment]
I see. Now it looks like the issue has more to do with connection pools. GAE probably doesn't allow that.

**Comment by nickoala** [comment]
You can always configure telepot to use a stand-alone connection for each requests. See my latest comment in #87.

**Comment by Suyash458** [comment]
Great. Thanks for helping out!
