### ISSUE TITLE
Suppress Telegram server http timeout warnings

### ISSUE THREAD

**Issue by beta48** [nickoala/telepot#124]
Hi,
Telepot is really great in functionality and documentation. I am currently using the stable version 7.1 to buypass the bug of 8.1 of occasional connection error and shutdown (discussed here).

From time to time, the telegram server seems to be quite busy and the regular GetUpdate requests (according to your tutorial) result in http timeout warnings ("Read time out"). That does not shutdown the programm but produces a lot of warning lines  on the screen. Is it possible to suppress these timeouts completely or at least reduce them to one line, maybe as logging.warning("...")?

**Comment by nickoala** [comment]
It prints out the stack trace because of this segment in the method `message_loop()`:

```python
def get_from_telegram_server():
    offset = None  # running offset
    while 1:
        try:
            result = self.getUpdates(offset=offset, timeout=timeout)

            if len(result) > 0:
                offset = max([handle(update) for update in result]) + 1
        except:
            traceback.print_exc()  ####### print stack trace on error
        finally:
            time.sleep(relax)
```

It would be nice to be able to override `get_from_telegram_server()` and change its behavior. Unfortunately, the way I structure it, it is impossible to override.

Another approach I can think of, is to wrap some error-handling code around `self.getUpdates()`, like this:

```python
def suppress_http_timeout_warnings(fn):
    def w(*args, **kwargs):
        try:
            response = fn(*args, **kwargs)
            return response
        except WhateverErrorYouWantToSuppress:
            print('a single line ...')
            return []
        except:
            raise
    return w

bot.getUpdates = suppress_http_timeout_warnings(bot.getUpdates)
```

Haven't tested it, but should not be far off. This is very similar to extending the `Bot` class and overriding its `getUpdates()` method. I hope you see the strategy.

Good luck.
