### ISSUE TITLE
how to update NOT update in the message_loop

### ISSUE THREAD

**Issue by luckyvictor** [nickoala/telepot#129]
From all the examples, seems like the bot is waiting at the background and listen to any incoming msg by bot.message_loop(handle).

Now I am actually creating my program and bringing the telepot in, the telepot is there to listen for any request from a remote user, and calls a function in my main program.

I don't need the bot to keep looping at the back to listen for a request, I just need to call it whenever my program calling a certain function.

so my question is, do I still use message_loop(handle) in this certain function please? or I just need to do an update and check the message? 

I tried the later and the update actually return me the same thing everytime, that to me seems like the user sends a request once, and the request stays forever until a new one, but my bot should only react at the first time it sees this request.

Another question I have is, how bot.message_loop(handle) actually runs? where does the handle object comes from? I just know that I have a def handle(msg), but it is a function.

Many thanks for helping me

**Comment by zumoshi** [comment]
hello,
you don't have to use the message loop. it's just there for your convenience. getting the same message again when manually calling get updates is not a bug. you need to give the get updates method an offset to skip messages that you have seen. you can read more about it here : https://core.telegram.org/bots/api#getupdates

> In order to avoid getting duplicate updates, recalculate offset after each server response.

for your second question, the handle is exactly that function that you have in your code. it doesn't have to be called handle, you can call it whatever you want. telepot calls that when a new message is sent to your bot to "handle" the message.

as for how it works you can check out the source:
https://github.com/nickoala/telepot/blob/master/telepot/__init__.py#L491

it may seem a little complicated because it has many options and works for both webhook and normal mode, but it basically calls get updates in a loop and calls your handle function every time a new message is received.

**Comment by luckyvictor** [comment]
@zumoshi 
Than you for providing me such a detail answer.

For the first one, I will try later. 

For the second one, are you bascially saying bot.message_loop(handle) is taking a function as is input? and this handle is a function with no return value? and I don't have to say bot.message_loop(bot.handle)?

I am new to coding, so forgive me if I am answer stupid question.

**Comment by zumoshi** [comment]
> are you bascially saying bot.message_loop(handle) is taking a function as is input? and this handle is a function with no return value?

yes, this way of using a function as an argument to another method is usually called a `callback function`. you can read more on them here:
http://stackoverflow.com/a/6289656/1461004
https://en.wikipedia.org/wiki/Callback_(computer_programming)

> and I don't have to say bot.message_loop(handle)?

correct. but if you don't write that in your code the message loop won't run, but you may still manually use `getUpdates` method to retrieve messages.

**Comment by luckyvictor** [comment]
I see, I think I can understand the first question as put two statements in one, e.g result = handle(), bot.message_loop(result).

So that raises another question, I see from the examples, the handle is usually defined as def handle(msg):, where does this msg come from?? by calling bot.message_loop(handle), I am not giving any value of msg to the function...

To use getUpdates, should I do
def handle(msg):
      xxxxxxx

result = bot.getUpdates(offset=100000001)
handle(result)

**Comment by zumoshi** [comment]
> result = handle(), bot.message_loop(result)

no , not exactly. did you read on the links i provided ?

there is a difference between
```python
bot.message_loop(handle())
```
and
```python
bot.message_loop(handle)
```
what you wrote in two statements is the first one.

the first one executes the handle and sends it results to the `message_loop` however, the second one doesn't execute the `handle`. it sends the function itself, thus allowing the message_loop to execute the `handle` when a new message is sent to the bot. the `msg` object is given to the handle inside the message loop.

this is a simple implantation of `message_loop`, the real one basically does this but with some more code for error checking and routing and other stuff.
```python
def message_loop(handle): # handle is the function handle itself, not its result
    offset = 0 # this is to prevent getting duplicate messages
    while True:
        # this is just a wrapper for telegram api, gets new messages
        messages = bot.getUpdates(offset=offset, timeout=10)
        if len(messages) > 0: # check if bot has recieved new message(s)
            offset = messages[-1]['update_id'] +1 #again to prevent duplicate messages
            for msg in messages: #get Updates can return multiple messages , so we need a for loop
                # this is the important part, handle function that is passed to message loop can 
                # be called from here, also here is where msg comes from
                handle(msg)
```

**Comment by luckyvictor** [comment]
Thank you! I think it is clear very now! 

So in this piece of code, the handle can be called without giving arg update? e.g callback = self.handle, and the result would be returned and saved in callback?

or ortherwise, if it is given, then this input arg would be update by return update['update_id']?

        if callback is None:
            callback = self.handle
        elif isinstance(callback, dict):
            callback = flavor_router(callback)

        def handle(update):
            try:
                key = _find_first_key(update, ['message',
                                               'edited_message',
                                               'callback_query',
                                               'inline_query',
                                               'chosen_inline_result'])

                callback(update[key])
            except:
                # Localize the error so message thread can keep going.
                traceback.print_exc()
            finally:
                return update['update_id']

**Comment by zumoshi** [comment]
> callback = self.handle, and the result would be returned and saved in callback?

it is not called there, functions are called when you have parentheses `()`, no parentheses means the function is not called/executed.

so if you have
```python
def a():
    return 2

b = a      # a is not executed, b is the function a
c = a()    # a is executed, c is a's result
```

here `c` is 4, but `b` is function `a`. not its result. you can then later call/execute `b`:
```python
d = b() # d will be 4
e = c() #<- this will result in error because you can't execute 4...
```

> So in this piece of code, the handle can be called without giving arg update?

in the code you provided `callback = self.handle` does not execute `self.handle`. it just stores the function itself in `callback`. then later you have `callback(update[key])` which is where `callback` or `self.handle` is called with the `update` arg.

so, no you can't call functions without their required arguments. however, you can store them in variables. not their results , the functions themselves. than later call them using their new name.

---

since this is mostly about python itself and not telepot perhaps [stackoverflow](http://stackoverflow.com) would be a better place to ask these questions?

**Comment by luckyvictor** [comment]
Appreciate for your tutorial. Since we have developed a conversation, I just think I may carry on asking all my questions.

I think that is about all the questions I have anyway, and I will test how to use getUpdates later. 

Many many thanks!!

**Comment by luckyvictor** [comment]
@zumoshi 

I would like to ask you a question again, possibly is just python related, but I am not able find the answer online yet.

I tried calling handle(msg), but I got an error saying: TypeError: list indices must be integers, not str, and my handle function looks like this

def handle(msg):
	chat_id = msg['chat']['id']
	command = msg['text']
	print 'Got command: %s' % command

I print the msg from bot.getUpdates(), and by seeing the structure of msg, I understand that it is a list that contains dictionaries, e.g. [{u'message': {u'date': xxx, u'text': u'Hiya', u'from': {u'first_name': u'xxx', u'last_name': u'xxx', u'id': xxxxxx}, u'message_id': 131, u'chat': {u'first_name': u'xxx', u'last_name': u'xxx', u'type': u'private', u'id': xxxxx}}, u'update_id': xxxxxxx}]

so my question is, how may I de-list it please? e.g. converting this msg into a form of {u'message': {u'date': xxx, u'text': u'Hiya', u'from': {u'first_name': u'xxx', u'last_name': u'xxx', u'id': xxxxxx}, u'message_id': 131, u'chat': {u'first_name': u'xxx', u'last_name': u'xxx', u'type': u'private', u'id': xxxxx}}, u'update_id': xxxxxxx}

Thanks in advance for helping me again.

**Comment by zumoshi** [comment]
i suggest that you read the following link:
http://www.tutorialspoint.com/python/python_lists.htm

it explains lists in python.

the thing is a list may contain more than one message in it , so you can't just de-list it. but you can either access only the first message (ignoring the rest) or execute your handle once for each message. if you read the simplified message_loop code that i gave you it already does that using a for loop.

you can also do it this way :
```python
updates = bot.getUpdates()
handle(updates[0]) # only the first message will be proccesed
# or
map(handle, updates) # all messages will be proccesed
```

**Comment by luckyvictor** [comment]
Many thanks! I actually managed to get it working by just doing handle(update) this time, but to be honest, I don't know why, here is my handle

def handle(msg,bot):
	chat_id = msg['message']['chat']['id']
	command = msg['message']['text']

**Comment by walldiE** [comment]
Hi also a bit new to python, the explanation above has been most helpful, but i'm stuck on one thing i cant seem to figure out how to check for a messages inside a while loop so that the message can break out of the loop,, inside the method "watching()". i also tried a different way lower in the "handle()" method but i can't seem to get it.

any help would be gr8 thanx


[myBot copy.txt](https://github.com/nickoala/telepot/files/822052/myBot.copy.txt)
