### ISSUE TITLE
Can't get admins list

### ISSUE THREAD

**Issue by efrenmanuel** [nickoala/telepot#136]
Whenever I try to use "getChatAdministrators(chat_id)"
It says that there is no suck command
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
>>> import telepot
>>> TOKEN="TOKENTOKENTOKENTOKENTOKENTOKEN"
>>> bot=telepot.bot(TOKEN)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'bot'
>>> bot=telepot.Bot(TOKEN)
>>> getChatAdministrators(chat_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'getChatAdministrators' is not defined
>>>
```

**Comment by zumoshi** [comment]
hello,
can you please provide your code and exceptions separately and using the [code format](https://help.github.com/articles/creating-and-highlighting-code-blocks/) ?
your current post is not clear, but from what i see you tried to use the global function `getChatAdministrators` instead of `bot.getChatAdministrators` which is a method of the bot object.

you can also see [this example](https://github.com/nickoala/telepot/blob/master/test/test27_admin.py) for how to use that method using python 2.

also please make sure to execute the following command first (if you haven't done already):
```
pip install telepot
```

if you got something like `pip is not recognized as an internal or external command...` please read [this question](http://stackoverflow.com/a/12476379/1461004)

**Comment by efrenmanuel** [comment]
Actually it works. thanks to that example I learnt to use it, before i just looked at the reference file, and i think that i got something wrong.
Sorry for making you lose your time.
