### ISSUE TITLE
Send Message via Telepot without parameter

### ISSUE THREAD

**Issue by Nadhzava** [nickoala/telepot#143]
Dear nickoala,i have read about your example here but i get problem when i try to send message without parameter 
E.g
def sendTele():
    count = 0
    global st
    f_time = datetime.now().strftime('%a %d %b @ %H:%M')
    with picamera.PiCamera() as camera:
        camera.resolution = (1024, 768)
        camera.start_preview()
        time.sleep(2)
        camera.capture('foto/photo'+f_time+'.jpg')
    #connect to our bot
    bot=telegram.Bot('xxxxx')
    #bot=telepot.Bot('xxx')
    #Wait for the first incoming message
    #updates=[]
    #while not updates:
    #bot.setWebhook()
    updates = bot.getUpdates()
    chat_id=updates[-1].message.chat_id     
   
    
    #Get the id for the active chat
    #print updates[-1].message.text
    #if chat_id == False:
    #    chat_id=updates[-1].message.chat_id
    #print chat_id
    #else:
    #    chat_id =  idi 

    #send message to the chat
    bot.sendMessage(chat_id=chat_id, text='Intruder detected! '+f_time)
    bot.sendPhoto(chat_id=chat_id,photo=open('foto/photo'+f_time+'.jpg'))       
    return count
Can you help me to find solution to execetue this function, im sorry cause i newbie here so i try to use other library e.g Telegram Bot not Telepot

**Comment by nickoala** [comment]
Are you sure you are using telepot? Even if you are, I can't help you until you better formulate your question.

**Comment by Nadhzava** [comment]
Sorry too late to answer,
My case like this:
I use telepot and synchronize that with raspberry,sensor PIR and pi camera
I want use telepot to send notifications to house owner if there are suspicious in her/him house.
I have tried use your tutorial and works but, there are problem,i must send commad first to telepot( i want it automatically without send command first)
Is there another way to for my case?

**Comment by zumoshi** [comment]
Hello,
you can send messages to users without replying to a command to notify them. however, there are two things to consider.

1. telegrams limitation on bots that you can only send messages to users that have clicked on start for your bot.

2. you need their user_id to send messages to them.

for this second case, getting the user id from getUpdates won't work , because getUpdates gets the recent messages the bot has received, if no messages are sent to the bot it will return an empty array.
you would want to store the userid, you can get your id from [@myidbot](http://telegram.me/myidbot) and put it directly in the code:
```python
bot.sendMessage(xxxxxxx, "test message")
```
without using getUpdates method at all.

or if you don't want to hardcode it, you can store the user's id in a file when they first send `/start` to your bot
```python
def handler(msg):
    if 'text' in msg and msg['text'] == '/start':
        with open('./id.txt', 'w') as f:
            f.write(str(msg['chat']['id']))
        bot.sendMessage(msg['chat']['id'],"Id saved")
bot = telegram.Bot('xxxxx')
bot.message_loop(handle)

#...
#... (somewhere else in the code when you want to send something)
#...

with open('./id.txt', 'r') as idfile:
    chat_id=int(idfile.read())
bot.sendMessage(chat_id, "Someone is in your house!")
```

ofcourse if you are already using a database, or a config file, storing it there might be better.
