### ISSUE TITLE
Too many requests, retry after 1

### ISSUE THREAD

**Issue by RockyTV** [nickoala/telepot#165]
I updated my bot code, and updated the dependencies as well.
After updating, my bot, hosted on OpenShift, will constantly crash with:

```
* Running on http://127.10.121.129:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "app.py", line 177, in <module>
    bot.setWebhook('https://pymariachi-xinayder.rhcloud.com/hook')
  File "/var/lib/openshift/574af7692d5271961e00014d/python/virtenv/venv/lib/python3.3/site-packages/telepot/__init__.py", line 634, in setWebhook
    return self._api_request('setWebhook', _rectify(p))
  File "/var/lib/openshift/574af7692d5271961e00014d/python/virtenv/venv/lib/python3.3/site-packages/telepot/__init__.py", line 398, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/var/lib/openshift/574af7692d5271961e00014d/python/virtenv/venv/lib/python3.3/site-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/var/lib/openshift/574af7692d5271961e00014d/python/virtenv/venv/lib/python3.3/site-packages/telepot/api.py", line 123, in _parse
    raise e(description, error_code, data)
telepot.exception.TooManyRequestsError: ('Too Many Requests: retry after 1', 429, {'error_code': 429, 'parameters': {'retry_after': 1}, 'ok': False, 'description': 'Too Many Requests: retry after 1'})
```

I tried contacting Telegram's bot support, but they said I was setting the callback multiple times, when I am not (or I think so). In case anyone's interested, [here's my code](https://github.com/RockyTV/mariachi.py/blob/master/app.py)

I don't know why this is happening. Everything is the same since I last updated my bot.

**Comment by wubai0709** [comment]
a quick way to fix this....

In updater.py, insert "sleep(1)" after line 317 to prevent sending setWebhook for clean and making connection in a short time.

**Comment by garciaw** [comment]
I'm also having the same error, started on Sept 23rd out of nowhere. My bot is hosted on Heroku, and the error happened even when I specified to use Telepot 8.3

setWebhook() with no arguments raises no exception
Manual setWebhook with curl sets it successfully
Long-polling raises no exception
The same error happens if I use the token for my test bot that is offline most of the time

In the end I set the webhook manually and commented out the command in my code. Is the webhook something you can just set and forget? (unless, of course, you change hosts or bot token)

**Comment by RockyTV** [comment]
I managed to fix it by importing time and setting it to sleep before each `setWebhook` call.

**Comment by garciaw** [comment]
Did you have `bot.setWebhook()` immediately followed by `bot.setWebhook('url')`?
I had it in my code from the [Heroku sample pull request](https://github.com/nickoala/telepot/pull/96/commits/dc8293fb223c203b3a7159892c429bfbe0993609). So it could be that this was all simply a server-side change to limit webhooking spam on Telegram.

**Comment by RockyTV** [comment]
No, I had the empty one being called before setting the URL. I have [updated my code, in case you want to take a look](https://github.com/RockyTV/mariachi.py/blob/master/app.py)

**Comment by garciaw** [comment]
Oops, sorry, I was too focused on the problem and forgot that you posted your code.
But that's what I meant, an empty *setWebhook*, and next line one setting the URL. I also had it like yours, without any sleep between calls.
So it seems the error is just Telegram implementing a limit for the rate you can set (and unset) webhooks.

**Comment by nickoala** [comment]
Hi guys, thanks for diagnosing the problem. I first thought it had something to do with my setting `retries=3` in `urllib3` since 9.0. Relieved to see that the problem lies somewhere else.

Out of pure curiosity, why do you need `setWebhook()` before `setWebhook(url)`? Telegram seems completely ok with you changing URLs like this:
```python
>>> bot.setWebhook('https://k.whatever.org/abc')
True
>>> bot.setWebhook('https://k.whatever.org/abcde')
True
```
It seems there's no need to unset it before setting it.

**Comment by garciaw** [comment]
Initially I had the bot running locally with long-polling Then when researching how to make it work on Heroku, I found the Heroku Sample code I mentioned above, and it had the lines

    BOT.setWebhook() # unset if was set previously
    BOT.setWebhook(URL + SECRET)

I just never questioned it and also included it in my code, since I am still a complete newbie when it comes to connectivity in apps.

**Comment by RockyTV** [comment]
Same for me, I saw the Heroku example and it cleared the webhook before setting it again, so I added it to my code.

**Comment by nickoala** [comment]
Ok, so it seems this line is NOT needed:
```python
bot.setWebhook()
```
To set webhook URL, you only need this line:
```python
bot.setWebhook(URL + secret)
```
And you can forget about all those `time.sleep(...)`.

I seldom use webhook myself, so the above comment is only *as far as I can see*.

**Comment by Noammac** [comment]
I still get the error. I'm hosting on Heroku and my code is
```python

bot.message_loop({'chat': on_get_message}, source=UPDATE_QUEUE)


@app.route(SECRET, methods=['POST', 'GET'])
def pass_update():
    UPDATE_QUEUE.put(request.data)
    return 'OK'

sleep(5)
bot.setWebhook(URL + SECRET)
```
(added more than the two last lines for context since it might be wrong)
I still get the error although I tried to `sleep()` before the `setWebhook()` **and** before the `setWebhook(URL + SECRET)`, and some other variations of `setWebhook()` and `sleep()`

**Comment by leninmedeiros** [comment]
@Noammac any news? I'm facing the same here

**Comment by Noammac** [comment]
Nope. Not a single change, the bots work for one second before erroring and
dying

**Comment by b0g3r** [comment]
same problem:
heroku, setWebhook and TooManyRequests

**Comment by Noammac** [comment]
I erased the setWebhook line and committed it, and it worked! The bit
responds to messages and I can see it logging in the console.
