### ISSUE TITLE
Keyerror when creating a Message

### ISSUE THREAD

**Issue by pymaldebaran** [nickoala/telepot#166]
I wanted to use the very convenient telepot.namedtuple to have more readable code. It worked perfectly with InlineKeyboardMarkup and InlineKeyboardButton but when trying to use Message I always got a KeyError regarding the 'from' field.
Te simplest way to reproduce the error is simply to try to create an empty Message tuple:
```python
>>> from telepot.namedtuple import Message
>>> msg = Message()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/telepot/namedtuple.py", line 28, in __new__
    kwargs[newkey] = kwargs[oldkey]
KeyError: 'from'
>>> msg = Message(from_='aaa')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/telepot/namedtuple.py", line 28, in __new__
    kwargs[newkey] = kwargs[oldkey]
KeyError: 'from'
```
It must have something to do with the 'from_' to 'from' conversion somewhat but I can't figure out how to circumvent the problem... I can't decide if this is a bug or that I'm not using the namedtuple correctly.

**Comment by nickoala** [comment]
I am glad you are aware of the `from_` field due to collision of the keyword `from`, although that is unrelated to your problem.

`Message` is meant to convert an *incoming* dictionary (representing a message) to an object. In other words, you should construct it from a dictionary:

```python
>>> from telepot.namedtuple import Message
>>> d = {'from': {'id': 999, 'first_name': 'Nick'}}
>>> m = Message(**d)
```

In real life, you should not need to compose that dictionary yourself. You should have gotten it from the argument to message handlers, e.g. the `msg` argument to `on_message()`, etc.

**Comment by pymaldebaran** [comment]
Ok so I was in fact using the namedtuple in a way it was not intended.

For the record, I was using it to build messages "manually" in the unittests for my bot. So maybe I will continue to use dict to do so (and wrapping them in a Message named tuple as you suggest) or try to Create a "FakeMessage" named tuple that can be used directly (I will have to dig into your Message code but it shouldn't be to hard… I hope).

Anyway thanks a lot and if ever you have any hints about how to modify the Message code to make it "empty constructorable"… it would be great :) Anyway thanks a lot for your wonderful work on Telepot.

**Comment by nickoala** [comment]
The namedtuple classes are not created directly using `collections.namedtuple()` because, with so many object types, that would result in a lot of duplicate code. `collections.namedtuple()` is still used under the hood, but it is wrapped in the `_create_class()` function, whose jobs include (but not limited to):

- translate `from` field to `from_` field
- give a default value of `None` to fields that have no default value specified
- recursively convert dictionary into namedtuple object for non-simple fields. For example, to place a `User` object or `Chat` object where appropriate. This recursive conversion is only done for *incoming* dictionary (e.g. `Message`). For *outgoing* objects (e.g. `InlineQueryResultArticle`), you are supposed to fill in the appropriate objects yourself.

Ideally, if you want to create an empty `Message()`, it *should* work because all absent fields should be defaulted to `None`. It is not *meant* to be created this way, but it should work. Just like a `Video` object (another incoming object), you get no error doing it this way:
```python
>>> from telepot.namedtuple import Video
>>> v = Video()
>>> v
Video(file_id=None, width=None, height=None, duration=None, thumb=None, mime_type=None, file_size=None, file_path=None)
```

Unfortunately for `Message`, the `from_` field complicates matters. In module `telepot.namedtuple`, I use this line to create a mapping between `from_` and `from`:
```python
keymap = [(k.rstrip('_'), k) for k in filter(lambda e: e in ['from_'], field_names)]
```
then do the replacement in the passed-in keyword arguments:
```python
for oldkey, newkey in keymap:
    kwargs[newkey] = kwargs[oldkey]
    del kwargs[oldkey]
```
A `KeyError` thus occurs if the passed-in keyword arguments have no `from`, *before* the default value can take effect. 

In real life, if `Message` is used according to intention, the `KeyError` would never occur because the `from` field always exists in a message. 

So, this may be called a bug, or it may not, depending on how robust you want telepot to be. (I am inclined to say "yes, it's a bug, because the supposed default value is not taking effect.")

To fix the root of the problem, I think this would do:
```python
for oldkey, newkey in keymap:
    if oldkey in kwargs:
        kwargs[newkey] = kwargs[oldkey]
        del kwargs[oldkey]
```
After this change. `Message()` should work. But `Message(from_=...)` still would not, because it always expects the untampered `from` in the original keyword arguments.

**Comment by nickoala** [comment]
Oops, I think `Message(from_=dictionary)` would work, because it will just skip the `from` and use the `from_`. However, you have to supply a **dictionary** because it expect a `User` in that field.

**Comment by pymaldebaran** [comment]
Thanks a lot, I now understand what was the exact problem (I tried by myself but I couldn't sort out a solution without breaking everything). You're right some of the fields have to be dictionaries... so creating "fake messages" can be quite cumbersome: I would have to build my messages with explicit instanciation of each sub structure (User, Chat...) just to be sure... overkill for a unittest helper. What I really needed was a convenient way to simply create Teleport like data structure using keyword arg syntax and automatic checking of the existence of the provided keys in the reference Teleport structure... telepot.namedtuple provide me the structure... so I need a workaround...

So with this brand new understanding of the situation I managed to find a solution that fits my problem well (without altering telepot's code) :
```python
def FakeMessage(**kwargs):
    """
    Helper pseudo type to create fake Telegram messages.

    Returns:
        A dict compatible with Telegram definition of a message.
    """
    # Preconditions
    assert all([key in Message._fields for key in kwargs])
    assert 'from_' in kwargs

    # Work around the fact from is a reserved word and can't be used as
    # parameter name
    kwargs['from'] = kwargs['from_']
    del kwargs['from_']

    return kwargs

def FakeChat(**kwargs):
    """
    Helper pseudo type to create fake Telegram chat.

    Returns:
        A dict compatible with Telegram definition of a message.
    """
    # Preconditions
    assert all([key in Chat._fields for key in kwargs])
    assert 'id' not in kwargs

    # KISS way to have a unique id for each chat
    kwargs['id'] = hash(time.time())

    return kwargs

def FakeUser(**kwargs):
    """
    Helper pseudo type to create fake Telegram user.

    Returns:
        A dict compatible with Telegram definition of a message.
    """
    # Preconditions
    assert all([key in User._fields for key in kwargs])
    assert 'first_name' in kwargs
    assert 'id' not in kwargs

    kwargs['id'] = hash(kwargs['first_name'])

    return kwargs

msg = FakeMessage(
    chat=FakeChat(type='text'),
    from_=FakeUser(
        first_name='Joey',
        last_name='Tribbiani',
        username='@friendsjoey'),
    text=txt)
```
This doesn't really use the namedtuple but they provide the "reference" I need to be sure not to create awful Frankenstein monsters by mistake while testing my bot. And this even gives me a good place to put my "dummy id" generation code.

Independently from this very specific problem of mine (now solved) I think the change you proposed to enable the creation of Message the same way the other namedtuple could be created would really be a real improvement to telepot.
