### ISSUE TITLE
Default timeout / WaitTooLong

### ISSUE THREAD

**Issue by leplatrem** [nickoala/telepot#2]
(*some doc feedback*)

I ran the example from the Python3 section. I did not set any timeout option, but yet I see those errors:

```
ERROR:root:on_close() called due to WaitTooLong: 
```

And the message counter always returns 1.

Although the documentation says:

> If the timeout option is set, it will raise a WaitTooLong exception after that many seconds.
> If the timeout option is not set or is None (default), it will wait forever.

It's probably a doc/default value adjustement :)

**Comment by nickoala** [comment]
The (async) Message Counter example on Python 3.4.3 contains these lines:

```python
bot = telepot.async.DelegatorBot(TOKEN, [
    (per_chat_id(), create_open(MessageCounter, timeout=10)),
])
```

which explicitly set the timeout to 10 seconds. Once you send the first message (to initiate the counting), if you don't send another message in 10 seconds, it will raise a `WaitTooLong` exception and terminate the counting.

I re-test that example, and here is what I got:

![screenshot_2015-11-28-11-28-36](https://cloud.githubusercontent.com/assets/13035417/11449990/49987a7e-95c6-11e5-9355-2496a9801899.png)

Notice the time of messages. After the first three messages, I wait a bit longer to send another. The original counting was terminated, so it re-started from 1.

It is recommended that timeout is not `None`, because if the user leaves the conversation at any time, that thread or task will hang there forever.

**Comment by leplatrem** [comment]
Thanks for the feedback! I realize now that setting a timeout is the most appropriate!
