### ISSUE TITLE
How to get 'new_chat_member' upon new user joining a group?

### ISSUE THREAD

**Issue by jeffffc** [nickoala/telepot#200]
I have been using the code well, but when i want to send some kind of welcome message upon a new member joining, i failed. What is wrong with my code?
the following is at the beginning of my `handle(msg)` function.
```
        g = telepot.glance(msg)
        if g[0] ==  'new_chat_member':
            print("NEW CHAT MEMBER")
```

`g[0]` returns 'chat' for normal messages, but it does not respond to new members joining and just prints this in my console:
```
/usr/local/lib/python3.5/dist-packages/telepot/namedtuple.py:49: UserWarning: Unexpected fields: new_chat_participant
Bot API seems to have added new fields to the returned data. This version of namedtuple is not able to capture them.

Please upgrade telepot by:
  sudo pip install telepot --upgrade

If you still see this message after upgrade, that means I am still working to bring the code up-to-date. Please try upgrade again a few days later. In the meantime, you can access the new fields the old-fashioned way, through the raw dictionary.
  warnings.warn(s, UserWarning)
```

**Comment by nickoala** [comment]
Why don't you add a couple print statements to see exactly what messages you are getting and what `glance()` returns?
```python
g = telepot.glance(msg)
print(msg)
print(g)

if g[0] ==  'new_chat_member':
    print("NEW CHAT MEMBER")
```
Then, you should have a better idea what happens.

As for that warning message, it is because Telegram leaves the field `new_chat_participant` in the message for backward compatibility, while the current standard uses `new_chat_member` instead. When you call the namedtuple `Message`'s constructor, it sees an unexpected field and prints a warning message. It's only a *warning* and should not stop your program from continuing.
