### ISSUE TITLE
CallbackQueryOriginHandler for different user groups

### ISSUE THREAD

**Issue by a1mo** [nickoala/telepot#254]
Hi!
How i can separate `CallbackQueryOriginHandler` for different ids like `per_chat_id_in` and `per_chat_id_except`?
for example:
```python
bot = telepot.aio.DelegatorBot(TOKEN, [
    pave_event_space()(
        per_chat_id_in(s = IdsController.masters), create_open, MasterHandler, timeout=config.sessionTimeout),
    pave_event_space()(
        per_chat_id_except(s = IdsController.mastersAndCandidates), create_open, ChatStarter, timeout=10),
])
```
I found only `per_callback_query_origin` and `per_callback_query_chat_id`

**Comment by nickoala** [comment]
Telepot does not have such a function, but you can always make your own. Let me walk you through my thinking process. 

Normally, you would do it like this:

```python
bot = Delegator.Bot(TOKEN, [
    pave_event_space()(
        per_callback_query_origin(), create_open, SubclassOfCallbackQueryOriginHandler, timeout=10),
])
```

`per_callback_query_origin()` ensures only one object of `SubclassOfCallbackQueryOriginHandler` is spawned for each *callback query origin*, which is the message that gives rise to such callback query. The origin can be an inline message or a regular chat message. Since you are asking to differentiate between chat id, I assume your callback query are originated from regular chat messages.

`per_callback_query_origin()` fails to satisfy you because it does not differentiate between chat id. To do that, you can add some logic surrounding `per_callback_query_origin()`, in effect inventing your own **[seeder](http://telepot.readthedocs.io/en/latest/reference.html#delegatorbot)** function:

```python
from telepot.delegate import per_callback_query_origin, _wrap_none

def per_callback_query_origin_for_chat_id_in(s):
    origin_extractor = per_callback_query_origin()

    def f(msg):
        if msg['message']['chat']['id'] in s:
            # act like per_callback_query_origin() only if chat id satisfy your requirement
            return origin_extractor(msg)
        else:
            return None

    # Not every message has the field ['message']['chat']['id'].
    # Use _wrap_none() to catch KeyError and return None instead.
    return _wrap_none(f)
```

Then, use it like this:

```python
some_chat_ids = set()

bot = Delegator.Bot(TOKEN, [
    pave_event_space()(
        per_callback_query_origin_for_chat_id_in(some_chat_ids), create_open, SubclassOfCallbackQueryOriginHandler, timeout=10),
])
```

`per_callback_query_origin_for_chat_id_except(set)` can be implemented likewise.

I have not tested the above code, but that's how I think about it. Hopefully it's not far off from what you want. Good luck.
