### ISSUE TITLE
deleteMessage notworking

### ISSUE THREAD

**Issue by ORcxzjeeeee** [nickoala/telepot#255]
hi
i have this issue
when i using deleteMessage its gives me error:

```
- bot.deleteMessage(message_id)
- Bad Request: chat identifier is not specified', 400,
```

when i set chat identifier its give another error:

```
- bot.deleteMessage(chat_id, message_id)
- deleteMessage() takes 2 positional arguments but 3 were given
```

**Comment by garciaw** [comment]
As the [docs](http://telepot.readthedocs.io/en/latest/reference.html#telepot.Bot.editMessageText) say, a `msg_identifier` is "a 2-tuple (`chat_id`, `message_id`), a 1-tuple (`inline_message_id`), or simply `inline_message_id`."

Since you are trying to give it the `chat_id`  / `message_id` pair, you should do it as a tuple:

`bot.deleteMessage((chat_id, message_id),)`

It's a subtle but important detail of the Python language. Your second example gave the function 2 positional arguments (not including the implied `self`): `chat_id` and `message_id`. 
My example gives 1 positional argument: a tuple that contains the `chat_id` and `message_id`. You need the extra parentheses and comma for Python to understand it this way.

**Comment by ORcxzjeeeee** [comment]
Thanks @garciaw!
my mistake.
I'll mark this as closed.
