### ISSUE TITLE
sendDocument cache problem

### ISSUE THREAD

**Issue by DavidePajot** [nickoala/telepot#279]
I want to send a pdf file that changes every day, but always send the same file even though the content of the pdf has changed, how do I fix the problem?

bot.sendDocument(chat_id, 'http://site.com/file.pdf')

**Comment by das7pad** [comment]
You could pull the file manually and cache it with the timeout of your choice - or even do not cache it, which I would not suggest.

**Comment by DavidePajot** [comment]
Can you show me an example please?

**Comment by das7pad** [comment]
You could use ``requests.get`` to fetch a remote source when using the synced telepot version or ``aiohttp.request`` with the async telepot version. Futher reading can be found in the documentation of each package.
The cache could be implemented with a dict, storing the urls as keys and as value a tuple with the last access timestamp (e.x. via ``time.time()``) and A a local path you downloaded the remote file into or B a file-like object with the raw file content.

**Comment by abadroot** [comment]
I think the issue is on Telegram Bot API side.

Try to download locally the GIF at http://www.arpa.veneto.it/previsioni/radar_concordia/anim_250.gif
and send on Telegram 
`bot.sendDocument(chat_id, "http://www.arpa.veneto.it/previsioni/radar_concordia/anim_250.gif")`
you have different images

The statement "Provide Telegram with an HTTP URL for the file to be sent. Telegram will download and send the file" (https://core.telegram.org/bots/api#sending-files) is wrong.
