### ISSUE TITLE
Infinite recursion issue in Exceptions

### ISSUE THREAD

**Issue by Scratchcat1** [nickoala/telepot#316]
https://github.com/nickoala/telepot/blob/89a459a49eb1725ffe678006e5e975e8777710e2/telepot/exception.py#L46-L50
It seems as if a `BadHTTPResponse` in the exception.py module will keep calling its own `__str__` method recursively until a `RuntimeError: maximum recursion depth exceeded` occurs.
Launching excpetions.py and calling this function in the shell will result in the recursion error.
```
try:
	raise BadHTTPResponse("test","test","test")
except Exception as e:
	print(e)
```

**Comment by nickoala** [comment]
Thanks.

The reason I override that was because, in the old days, if you supply an obviously wrong token, Telegram redirects to the Bot API home page and gives you an entire page of HTML. To avoid excessive output, I override that to output only the first 500 characters, and made such a terrible mistake in the process.

Today I checked again, it seems Telegram has changed to give a much better response in case of a wrong token. It actually returns a valid JSON object, causing a `TelegramError`.

So, it seems restricting output to 500 characters is no longer necessary. I will take the easy way out and *not* do the override at all, thus eliminating the infinite recursion.

Thank you for pointing out this obvious and terrible mistake :blush:
