### ISSUE TITLE
Inline query examples errors on empty inline query

### ISSUE THREAD

**Issue by amathael** [nickoala/telepot#332]
I have found out that inline.py and inlinea.py are not working correctly right after you start a message with `@<botname>`. It seems that they are not able to work with InlineQuery with empty message, depending on 
> File "C:\Program Files\Python36\lib\site-packages\telepot\api.py", line 150, in _parse raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: message text is empty', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: message text is empty'})

Yes, it doesn't affect the flow of the program and after this error it runs correctly, but maybe you should do something with this.
I'm a beginner in GitHub, so, maybe, if you think it's ok I can try to find a way to fix it as my first GitHub contribution, or, maybe, if not ok, I can try to just fix examples

**Comment by nickoala** [comment]
You are correct. It is because `inline.py` only takes your query string and echoes it back in the response. Telegram does not allow empty strings in the response's title and message, resulting in the error you saw.

I have known about this problem since very long ago, and it is easy to fix. But I never have the motivation to fix it because (1) this is only a very trivial *example*; and (2) it is not so bad to let users see this error and make them aware that some fields should not be empty.

Just remember to always type something after `@WhateverBotItIs`. A little bit of an annoyance, but also a little bit of a learning experience :blush:
