### ISSUE TITLE
Stop listening messages when the script was off

### ISSUE THREAD

**Issue by DrumSergio** [nickoala/telepot#35]
Goog morning!

I would like to know if something has been made to stop Telegram send me old messages when the python script of telepot was off. I need it because it's intended to open doors, and in case something happens that takes my server off, I don't want the software to be opening doors at 3am (when, for example, the server comes back online) while everybody is sleeping.

I explained the issue [here](https://groups.google.com/forum/#!topic/telepot/3_kvHl5v18Y) but got no answer yet.

**Comment by zumoshi** [comment]
hello,
the message object sent by telegram bot api contains a date property , you can check against current time this and ignore the message if it is older than say 10 minuets
https://core.telegram.org/bots/api#message 

hope this helps.

**Comment by nickoala** [comment]
@zumoshi gives one possibility.

Another possibility is, before calling `notifyOnMessage()` or `messageLoop()` (async version), you clear old messages first:

```python
updates = bot.getUpdates()

if updates:
    last_update_id = updates[-1]['update_id']
    bot.getUpdates(offset=last_update_id+1)

bot.notifyOnMessage()
```

I am considering adding an option to `notifyOnMessage()` to tell it to skip initial messages. Let me sleep on it for a few nights. :smile:

**Comment by nickoala** [comment]
Here's my thoughts:

1. I could add an option to `notifyOnMessage()` to tell it to skip the first batch of messages. However, this concept only applies to `getUpdates()` and is not applicable to webhooks, because webhooks don't receive updates batch by batch. Webhooks get pushed messages by Telegram servers continuously. It is impossible to say which messages are "initially present" and which are not. There is nothing wrong with an option that applies only to some selected circumstances, but in this case, I think the benefit is too small to justify the asymmetry.

2. I could add an option to `notifyOnMessage()` to tell it to ignore messages before a certain time. This would apply to both `getUpdates()` and webhooks, but another asymmetry happens. `InlineQuery` and `ChosenInlineResult` do not have a time; only normal chat `Message` does. Again, I could apply the time criteria to `Message` only. But again, I think the benefit is too small to justify the trouble.

Therefore, I have decided telepot will not touch this problem. You will have to take care of it yourself.
