### ISSUE TITLE
Editing message sent once inline_query article has been chosen.

### ISSUE THREAD

**Issue by Dextroz** [nickoala/telepot#423]
When using an inline bot it returns article(s). Once an article has been selected by the user; a message is returned based on this code:
`articles = [{'type': 'article', 'id': 'abc', 'title': query_string, 'message_text': 'Some Message here'}]`
**I want to be able to edit this message sent.**

I have been looking at the documentation and see the [message_identifier](https://telepot.readthedocs.io/en/latest/reference.html#telepot.message_identifier) method.
It says `msg is expected to be chat or choson_inline_result`. However, so far I have not been successful in it's usage.

One example I have tried:
`
async def on_chosen_inline_result(self, msg):
    inline_message_id = telepot.message_identifier(msg)
`

Can someone explain to me what I'm doing wrong?

Thanks!

**Comment by nickoala** [comment]
It's been a while since I made all that stuff (and I am not actively maintaining them), so my memory is a little fuzzy. I suspect you cannot edit such a message, but I may be wrong.

Can you help me by trying out the file `inline.py` in the `examples/inline` directory? It is a simple example of inline query, and prints out the ChosenInlineResult when user makes a choice. Can you tell me what the ChosenInlineResult looks like?

The key is whether it contains the field `inline_message_id`. If it does not, then editing would not be possible. Even if it does, I am not sure it points to an editable message. Let's see if the field `inline_message_id` is present. If not, we can be sure it cannot be edited.

**Comment by Dextroz** [comment]
Hey @nickoala 

I executed the inlinea.py from the examples.

The message itself is as follows:
`{'from': {'first_name': 'name here',
          'id': 531542910,
          'is_bot': False,
          'language_code': 'en-GB',
          'username': 'username here'},
 'location': {'latitude': float here, 'longitude': float here},
 'query': 'test',
 'result_id': 'abc'}`

By the `ChosenInlineResult` I assume you are referring to the print statement:
`531542910 : Chosen Inline Result: abc 531542910 test`

Dextroz.

**Comment by Dextroz** [comment]
> In other words, in order to get an inline_message_id which enables you to edit a message, you first have to give a reply_markup to an InlineQueryResult. If you do that, the ChosenInlineResult (after user making a choice) should contain an inline_message_id.

Adding a simple InlineKeyboardButton and doing as you said has solved the issue. Doing this obtains the `inline_message_id`. Thanks for the help @nickoala.
