### ISSUE TITLE
Sending files larger than 50MB via this library

### ISSUE THREAD

**Issue by iyuvalk** [nickoala/telepot#430]
Hi,

First of all, thanks a lot for all the hard work. This library is great and simple and intuitive. What a great combination!!

I have a bot that runs using this framework and works great but I need it to send files that are larger than 50MB. I read that it is possible via the API (https://core.telegram.org/api/files) but is it also possible via this library?

Tnx
Yuval.

**Comment by nickoala** [comment]
The link you referred to applies to the Telegram API, not the Bot API. Bot API has its own limit on uploading files. If I remember correctly, the limit is 50MB. Since I don't maintain telepot any more, I haven't followed the latest development and am not sure if the limit has changed. Whatever limit is supported by the Bot API, telepot should be able to upload files of that size (or smaller).

**Comment by iyuvalk** [comment]
Thanks. The reason I referred to the Telegram API was because I hoped that there would be a way to bridge between the two and somehow allow the bot to send files larger than 50MB (this is indeed the limit) after reading your detailed comment I realize that I'll have to find other solutions for sending large files (like for example uploading the file to a Google drive and sending a link instead...)

Thanks a lot again,
Yuval.
