### ISSUE TITLE
Running flask and telepot.notifyOnMessage hangs application in GAE dev_appserver

### ISSUE THREAD

**Issue by jonathan-s** [nickoala/telepot#55]
If someone has any insight in this it would be much appreciated.

**Comment by Ocimum-basilicum** [comment]
Hi Jonathan
I started with GAE and telepot and couldn't get it running also. I'm not quite sure if this is correct but what I found out is that GAE doesn't allow you to spawn threads and telepot is using threads. Maybe checkout this [stackoverflow](http://stackoverflow.com/questions/3800435/why-does-google-app-engine-support-a-single-thread-of-execution-only)
I switched over to openshift (red hat cloud) and telepot works really good there!

**Comment by jonathan-s** [comment]
Thanks for confirming my experience. Though it feels like you should be able to run if you're using a managed vm? But since dev_appserver was quite tightly integrated to appengine I can understand that it wouldn't work while developing.

**Comment by nickoala** [comment]
Hi @jonathan-s, may I ask:

- are you using webhook?
- are you using `DelegatorBot`?

Depending on how exactly you are using it, there *might* be a way to *not* spawn threads.

I am going to sleep now, and will be busy tomorrow. So don't expect a quick response. :smile: After a few days of hard work updating telepot to support Bot API 2.0, I need some rest.

**Comment by jonathan-s** [comment]
Hi Nick,

Thanks for updating telepot! Essentially I used the pattern here before it
was updated:
https://github.com/nickoala/telepot/blob/master/examples/webhook_flask_counter.py

Brilliant examples that you have btw, really helps make it clear.


On Monday, April 18, 2016, Nick Lee <notifications@github.com> wrote:

> Hi @jonathan-s <https://github.com/jonathan-s>, may I ask:
>
>    - are you using webhook?
>    - are you using DelegatorBot?
>
> Depending on how exactly you are using it, there *might* be a way to *not*
> spawn threads.
>
> I am going to sleep now, and will be busy tomorrow. So don't expect a
> quick response. [image: :smile:] After a few days of hard work updating
> telepot to support Bot API 2.0, I need some rest.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nickoala/telepot/issues/55#issuecomment-211485489>
>


-- 
Sent from Gmail Mobile

**Comment by nickoala** [comment]
Background (in case you are not aware): There are two places where telepot spawns threads:

- the method `message_loop()`
- delegate creation, when we need to "fork" a separate line of execution

I have zero knowledge on Google AppEngine. But if you really want to try that example in a no-thread environment, I suggest making these modifications:

1. Ditch `message_loop()`. Call `handle()` directly. For example, in the flask application you do this instead:

    ```python
    @app.route('/abc', methods=['GET', 'POST'])
    def pass_update():
        update = json.loads(request.data)  # Python 2.7
        # update = json.loads(request.data.decode('utf-8'))  # Python 3

        bot.handle(update['message'])
        return 'OK'
    ```

    From my (perhaps out-dated) knowledge, that Flask webserver (as used in the example) only uses a single thread, so you don't have to worry about thread-safety when calling `handle()`.

2. Thread is the default way to "fork" a separate line of execution. It doesn't have to be. In the [chatbox](https://github.com/nickoala/telepot#examples-chatbox) example, I demonstrate how to spawn a custom thread:

    ```python
    class CustomThread(threading.Thread):
        def start(self):
            print('CustomThread starting ...')
            super(CustomThread, self).start()

    def custom_thread(func):
        def f(seed_tuple):
            target = func(seed_tuple)

            if type(target) is tuple:
                run, args, kwargs = target
                t = CustomThread(target=run, args=args, kwargs=kwargs)
            else:
                t = CustomThread(target=target)

            return t
        return f

    # You can't actually find the following lines in the example, but same idea.
    # Wrap the default with your custom version of forking.
    bot = telepot.DelegatorBot(TOKEN, [
        (per_chat_id(), custom_thread(create_open(MessageCounter, timeout=10))),
    ])
    ```

Instead of a custom **thread**, you can make up any version of "forking", whatever is supported in GAE (Task queue, from what little I've heard?). All that is required is you return an object that has two methods:

- `start()`
- `is_alive()` - to check whether it's finished

which is why `threading.Thread` is a natural fit.

All these may be quite confusing at first. It's up to you to decide whether it's worth the effort.
