### ISSUE TITLE
Running webhook_flask_skeleton.py locally

### ISSUE THREAD

**Issue by ninajlu** [nickoala/telepot#60]
I'm trying to run the flask skeleton locally

`python webhook_flask_skeleton.py TOKEN_KEY 8443 https://localhost:8443/abc`

However, when I run this, I get the following error:
`telepot.exception.TelegramError: (u'[Error]: Bad webhook: [Error]: Ip is reserved', 400, {u'error_code': 400, u'ok': False, u'description': u'[Error]: Bad webhook: [Error]: Ip is reserved'})`

Is this because of an ssh token or am I unable to use this port?
I originally only used 8443 because I got an error that said
`telepot.exception.TelegramError: (u'[Error]: Bad webhook: [Error]: Webhook can be set up only on ports 80, 88, 443 or 8443', 400, {u'error_code': 400, u'ok': False, u'description': u'[Error]: Bad webhook: [Error]: Webhook can be set up only on ports 80, 88, 443 or 8443'})`

**Comment by nickoala** [comment]
Your webhook has to be at a **publicly accessible URL** because Telegram pushes updates to that address. `localhost` is only accessible from your own machine.

**Comment by zumoshi** [comment]
I run the webhook bot locally, but you can't use `localhost` for that. to do that you need to first obtain your public ip address, than make sure you are not behind a NAT (and if you are configure port forwarding as needed).
if you are not familiar with networking concepts needed or don't have access to do these i suggest using a server<sup>[1](#myfootnote1)</sup> or if you don't want to expend money you can use [c9.io](http://c9.io) , which is a free service that allows you to run your code online for testing purposes without the hassle of configuring a local environment.

otherwise here are the steps to run a webhook bot locally:

1. get your public ip address 
    * hint: it does not start with 192.x.x.x or 127.x.x.x, and its not localhost
    * you can search google for "what is my ip" (note: you need to disable proxies before doing that)
    * note that depending on your isp it may change each time you restart your modem, so watch out for that and update accordingly the new ip on your bot
    * **\*optional*** if your ip changes you can use a dynamic dns service such as [noip](http://www.noip.com/) to prevent the need for modifying it each time

2. run a webserver at desired port to test if your computer is accessible. 
    - you can run the flask example without the line that sets the webhook
    - you can ask a friend to open https://YOUR_PUBLIC_IP or simply use [this site](http://www.yougetsignal.com/tools/open-ports/) to check, put 8443 or 443 based on the port you chose while testing
    - if your port was open than that's all, you can uncomment the webhook line and it works

3. if your port was closed: forward ports from WAN to your LAN ip
    - first check for firewalls on your pc, maybe you don't need to forward your port and flask is blocked by an antivirus or firewall
    - if that was not the case follow these steps:
        1. get your private ip address
            - you can use `ifconfig` in terminal on linux or `ipconfig` in cmd on windows to find it , it most likely starts with 192.168.x.x and is in front of `IPv4 Address`
        2. go to your modem's configuration and Forward desired port
            - you have to forward the port (e.g. 8443) to your local ip, since each modem has a different configuration i can't describe this step but there is an excelent website that covers most modem configurations : [portforward.com](http://portforward.com/english/applications/port_forwarding/Apache/default.htm). just select your modem model and you get a picture guide for port forwarding.
            - depending on your network configuration you may get a new local ip for your pc on each restart, so if it stopped working try checking to see if your local ip has changed and edit your port forward accordingly
4. check to see your port is [open now](http://www.yougetsignal.com/tools/open-ports/).
    - if it still was not open you may need to restart your modem for configuration to take effect.
    - try disabling your firewall temporarily to test if that's causing the issue
    - if you are using a vpn/proxy you need to disconnect it for this to work

you can read more about this here:

- http://superuser.com/a/961846/248136
- http://lifehacker.com/127276/geek-to-live--how-to-access-a-home-server-behind-a-routerfirewall
- http://www.thetechmentor.com/posts/how-to-host-a-web-site-from-your-computer/

_some of these link also include downloading/setting up a webserver , you can skip that since you already have flask just look at the parts about firewall/router_

<a name="myfootnote1">[1]</a>: there are very cheap options available for a server, Digital ocean for example takes only 5$ per month
