### ISSUE TITLE
Download Image

### ISSUE THREAD

**Issue by BogdanStanciu** [nickoala/telepot#65]
Hi. 
I have a problem to download a image whit telepot. I try to download an image that a user send, using `bot.download_file(file_id, path)` but give me error like this:
 `Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/telepot/__init__.py", line 414, in handle
    callback(update[key])
  File "provabot.py", line 16, in handle
    bot.download_file(p["file_id"], "/Users/user_name/Desktop/image");
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/telepot/__init__.py", line 388, in download_file
    d = dest if _isfile(dest) else open(dest, 'wb')
IsADirectoryError: [Errno 21] Is a directory: '/Users/user_name/Desktop/image'`
How i can fix it ?

**Comment by zumoshi** [comment]
Hello,
you need to give `download_file` method a full path including the **filename**, not just the folder to save the file in it.

i have succefuly saved an image sent to bot using the following handle function:
```python
def handle(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    if content_type == 'photo':
        bot.download_file(msg['photo'][-1]['file_id'], './file.png')
```

note that the example code overwrites new images on the old one, you may want to generate the file name dynamically instead of hard coding one.

note 2: `msg['photo']` is a list of different sizes of image, first element is a small thumbnail so i used `-1` (last photo) to get the photo with highest quality

**Comment by BogdanStanciu** [comment]
Thank you very much  !


2016-04-22 12:39 GMT+02:00 zumoshi <notifications@github.com>:

**Comment by bot9987** [comment]
and what happens when the photo you receive is a JPG? you will force save it as PNG and this can cause problems later.
