### ISSUE TITLE
Spam-Protection

### ISSUE THREAD

**Issue by Bart1909** [nickoala/telepot#68]
Hey,

i've built three bots, which pull new posts (images) from different facebook-pages and send them to the subscribers of the bot. 
This worked for all three bots. Since yesterday evening, one bot doesn't send any more pictures.
It sends textmessages but no photos. 
My function looks in all three bots similar like this:

def sendlastPhoto(chat_id):
	print("Start sending last photo")
	post = fbgraph.get_object(id='xxx/photos?limit=1')
	postid = post['data'][0]['id']
	print("PostID: " + postid)
	posturl = (fbgraph.get_object(id=postid+'/?fields=source'))['source']
	print("PostURL: " + posturl)
	f = urllib2.urlopen(posturl)
	print("PostURL2: " + str(f))
	bot.sendMessage(chat_id, text="Sending picture, please wait..")
	result = bot.sendPhoto(chat_id, (postid + '.jpg', f))
	print("Result: " + result)
	print("Finished sending last photo")

I've got a timeout when executing the command: bot.sendPhoto(chat_id, (postid + '.jpg', f))

The Bots are running as an Lambda Function at AWS.The Timeout is set to 30 seconds, but I've already increased the timeout to 100 seconds without success.

If I replace the bot-token in this Lambda Function where I get the Timeout-Error with another bot-token everything works. Looks like there is something like a spam-protection which prohibits my bot to send pictures....

Is there a solution for this problem?

Thanks!

**Comment by zumoshi** [comment]
hello,
I've also faced a similar problem at one of my bots. mine sends voice messages, but stopped working with `Readtimeout` error on file upload, strange thing is changing the token solves the problem so there is no problem with the server , or code , or even network connectivity of server. which is strange because there is nothing about such limitation (file upload per token) on telegram bot api docs.

have you tried contacting [@BotSupport](http://telegram.me/botsupport) ?

---

also if you are sending the same image many times you should try using the file_id to send it rather than re-uploading it, in my experience there is no limit on sending files using file_id.

**Comment by Bart1909** [comment]
hi,

i've already revoked the bot-token but without any success... 

so far i haven't used the file_id and re-uploaded the image several times. now, i've implemented to upload once and use the file_id.

I've contacted the @BotSupport, hope there will be an answer :-)

**Comment by Bart1909** [comment]
In the Bots FAQ there is a limit described:
The API allows not more than 30 messages per second. 
Or sending more than 20 messges per minute to the same group.

But I shouldn't have reached the limit, because at the moment (development phase) I'm the only subscriber....

**Comment by zumoshi** [comment]
if you hit that limit you will receive 429 errors on all messages, however in our case we can send text messages , only files fail. so i don't think it is related to that limit.
