### ISSUE TITLE
bot.notifyOnMessage(handle) (self handel set message as read.)

### ISSUE THREAD

**Issue by t-me** [nickoala/telepot#7]
Hello Nick Lee,

I realy love this script.
i'm working on this to control my PI.

But i am new to python and dont know how to handle at this point.
i'm working from the diceyclock.py

i have a command /reboot this works only the problem is that the message is not set read so when i start the script it wil reboot again and again.

i lookt in to _init_.py from telepot and found get_from_telegram_server() and see that it wil set the message as read (offset). But how can i implement it on this : 

    if command == '/restart':
        -- line to set message as read -- 
        bot.sendMessage(chat_id, str("rebooting in 3"))
        time.sleep(1)
        bot.sendMessage(chat_id, str("2"))
        time.sleep(1)
        bot.sendMessage(chat_id, str("1"))
        time.sleep(1)
        restart()

**Comment by nickoala** [comment]
There is not a trivial way to solve your problem, because the message handler does not have access to `offset` for `getUpdates()`. And there is really no way to control the calling of `getUpdates()` from within the message handler.

I can think of a few solutions, but need time to flush them out and test them. Just want to let you know that I understand your question. Give me a little more time. I will get back to you soon.

**Comment by t-me** [comment]
Thank you Nick Lee for your replay and i will be waiting on your answer.
Don't rush for me take some coffee or a beer sometime :)

**Comment by nickoala** [comment]
Ok, here we go.

Option 1: Implement your own `getUpdates()` loop. This way, you can access any variables you need. Just call `getUpdates()` with the proper offset before rebooting.

Option 2: Added the following code segments to your diceyclock example. The main points being:

- On receiving the `/reboot` command, you don't reboot right away. Instead, just remember the *need* to reboot.
- The actual rebooting is done after the next `getUpdates()`. I modify the bot's `getUpdates()` method to include a reboot check.

Given that you are following the diceyclock example, I think this solution is most suitable, involving the least amount of changes.

```python
to_reboot = False

def check_reboot(getUpdates):
    # Add a reboot check and call getUpdates() accordingly
    def r(*args, **kwargs):
        if to_reboot:
            # Eliminate `timeout` parameter so getUpdates() returns immediately.
            del kwargs['timeout']
            rtn = getUpdates(*args, **kwargs)
            subprocess.call('sudo reboot', shell=True)
        else:
            # Normally
            rtn = getUpdates(*args, **kwargs)

        return rtn
    return r

# Modify the getUpdates() method to include a reboot check
bot.getUpdates = check_reboot(bot.getUpdates)

def handle(msg):
    global to_reboot
    
    if to_reboot:
        # Anything received AFTER the /reboot command but BEFORE the machine
        # goes down will be ignored.
        return

    ......

    if command == '/reboot':
        # Do not reboot here. Just remember the need to reboot.
        # The actual rebooting is done in the modified getUpdates() method.
        to_reboot = True

    ......
```

Option 3: Same as option 2, but use an object-oriented approach:
- subclass the bot
- add a `to_reboot` member variable
- implement a `handle(msg)` method
- override `getUpdates()` method to include a reboot check

Having seen your problem, I have considered building in a way to better and more formally control looping. But since this problem is not common and can be worked around in above ways, I will hold it off for now.

Hope it helps. Thanks for using telepot.

**Comment by t-me** [comment]
Thanks Nick,

I will share my script when the reboot function is up and running.
Maybe other people can use it :)
