### ISSUE TITLE
per_chat_id() doesn't play well with callback queries

### ISSUE THREAD

**Issue by dudalev** [nickoala/telepot#94]
Hi!

per_chat_id() only checks for a chat id in msg['chat']['id'], while for callback queries (as specified in https://core.telegram.org/bots/api#callbackquery and seen in the wild), the corresponding chat id is going to be in msg['message']['chat']['id']. (at least for "normal", not inline messages)

Cheers, 

Michael

**Comment by dudalev** [comment]
Similarly, in ChatHandler constructor, capture criteria should be extended with
        self.listener.capture(message__chat__id=self.chat_id)

**Comment by nickoala** [comment]
I think you mix up [Update](https://core.telegram.org/bots/api#update) and [Message](https://core.telegram.org/bots/api#message). The former encapsulates the latter. The Bot API method `getUpdate` gives you Update objects, but telepot's `message_loop` would strip the "outer layer" and give you the Message object within.

`per_chat_id` (and most other functions in telepot) acts on Message, not Update.

Strictly speaking, an Update may encapsulate one of five types of objects. Those are reflected in their flavors:
- Message (flavor `chat`)
- Message (flavor `edited_chat`)
- [CallbackQuery](https://core.telegram.org/bots/api#callbackquery) (flavor `callback_query`)
- [InlineQuery](https://core.telegram.org/bots/api#inlinequery) (flavor `inline_query`)
- [ChosenInlineResult](https://core.telegram.org/bots/api#choseninlineresult) (flavor `chosen_inline_result`)

Everywhere in the documentations, I use the generic noun "message" to refer to all these types of objects. I hope the context and upper/lower-case of the first letter prevent any ambiguity.

By reading the title "per_chat_id() doesn't play well with callback queries", I think I can guess where your real problem lies. When you have a `ChatHandler` to deal with a private chat, you expect it to capture both of these:

1. a Message whose `msg['chat']['id']` is a certain number
2. a CallbackQuery whose `msg['from']['id']` is also that certain number

As of today (version 8.1), `ChatHandler` does exactly that, by default. (I am updating the docs. Please look at the source code for now.)

Almost all the time, `ChatHandler` is paired with `per_chat_id`, which causes a new `ChatHandler` to be born for every new `msg['chat']['id']` seen, matching case number (1) above. However, `per_chat_id` does not do the same for every new `msg['from']['id']` seen for CallbackQuery, creating an asymmetry with case number (2). (Please don't feel bad if you don't fully understand what I am saying. This issue requires a deeper understanding of telepot.)

It will be fixed in an upcoming version. I will also update documentations in light of all the recent changes of Bot API.

**Comment by nickoala** [comment]
For now, if you want a totally symmetric `per_something` opposite to the default `ChatHandler`, try this:

```python
def per_chat_id_with_callback_query():
    def w(msg):
        fv = flavor(msg)
        if fv in ['chat', 'edited_chat']:
            return msg['chat']['id']
        elif fv == 'callback_query':
            return msg['from']['id']
        else:
            return None
    return w
```

**Comment by nickoala** [comment]
Now that I really have time to play around with callback query, I think I appreciate your question better. It seems like I *might* have misunderstood your question. Regardless, you can ignore what I said above if you find it confusing and useless. **[A few more weeks](https://github.com/nickoala/telepot/issues/99) and things will become much clarified.**
